apiVersion: v1
kind: ConfigMap
data:
  policy.csv: |
    g, alice, role:readonly
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "1976"
  uid: 07bee674-9d25-4bca-9c77-dc7f799b6676
