apiVersion: v1
data:
  accounts.alice: apiKey,login
  accounts.alice.enabled: "false"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"accounts.alice":"apiKey, login","accounts.alice.enabled":"false"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"hailyeah2ebugaloo","app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd"}}
  creationTimestamp: "2024-04-20T12:07:42Z"
  labels:
    app.kubernetes.io/instance: hailyeah2ebugaloo
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "8406"
  uid: f36b2019-a9a7-48ad-9dfa-c678d813039a
