apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hailyeah
  namespace: default
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: Helm
    repoURL: 'https://github.com/Gilibee-goode/Hailyeah-ArgoCD.git'
    targetRevision: main
    # directory:
    #   recurse: false
  destination:
    # name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  sources: []
  project: default
  syncPolicy:
    # syncOptions:
    # - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
